"""add item_scores and max_possible_score to evaluation_rag

Revision ID: 2ed01dd1ee69
Revises: 610b6537dcd2
Create Date: 2026-03-06 01:12:46.925915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed01dd1ee69'
down_revision: Union[str, None] = '610b6537dcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_rag_evaluations', sa.Column('item_scores', sa.JSON(), nullable=True))
    op.add_column('evaluation_rag_evaluations', sa.Column('max_possible_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_rag_evaluations', 'max_possible_score')
    op.drop_column('evaluation_rag_evaluations', 'item_scores')
    # ### end Alembic commands ###
