"""add gov_news_crawler tables

Revision ID: 610b6537dcd2
Revises: e81c2b4c7085
Create Date: 2026-03-05 01:02:39.496947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610b6537dcd2'
down_revision: Union[str, None] = 'e81c2b4c7085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gov_keywords',
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('target_entities', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gov_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gov_articles',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('leader_name', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['gov_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gov_articles_url_hash'), 'gov_articles', ['url_hash'], unique=True)
    op.create_table('gov_crawl_runs',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keyword_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['gov_keywords.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gov_scores',
    sa.Column('rule_keyword_score', sa.Float(), nullable=False),
    sa.Column('rule_position_score', sa.Float(), nullable=False),
    sa.Column('rule_source_score', sa.Float(), nullable=False),
    sa.Column('rule_recency_score', sa.Float(), nullable=False),
    sa.Column('rule_total_score', sa.Float(), nullable=False),
    sa.Column('ai_relevance_score', sa.Float(), nullable=True),
    sa.Column('ai_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('keyword_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['gov_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['gov_keywords.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'keyword_id', name='uq_score_article_keyword')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gov_scores')
    op.drop_table('gov_crawl_runs')
    op.drop_index(op.f('ix_gov_articles_url_hash'), table_name='gov_articles')
    op.drop_table('gov_articles')
    op.drop_table('gov_sources')
    op.drop_table('gov_keywords')
    # ### end Alembic commands ###
