"""Add bid_order_plans, bid_pre_specs, bid_pipeline_links + extend bid_alerts

Revision ID: 78e7915b4746
Revises: e3f4a5b6c7d8
Create Date: 2026-04-28 04:56:07.659527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e7915b4746'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_order_plans',
    sa.Column('order_plan_unty_no', sa.String(length=80), nullable=False),
    sa.Column('bid_type', sa.String(length=20), nullable=False),
    sa.Column('prdct_clsfc_no_nm', sa.String(length=1000), nullable=True),
    sa.Column('asign_bdgt_amt', sa.Float(), nullable=True),
    sa.Column('ordr_plan_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordr_yymm', sa.String(length=8), nullable=True),
    sa.Column('ordr_instt_cd', sa.String(length=20), nullable=True),
    sa.Column('ordr_instt_nm', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('source_keyword', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_order_plans_order_plan_unty_no'), 'bid_order_plans', ['order_plan_unty_no'], unique=False)
    op.create_table('bid_pre_specs',
    sa.Column('bf_spec_rgst_no', sa.String(length=80), nullable=False),
    sa.Column('bid_type', sa.String(length=20), nullable=False),
    sa.Column('prdct_clsfc_no_nm', sa.String(length=1000), nullable=True),
    sa.Column('asign_bdgt_amt', sa.Float(), nullable=True),
    sa.Column('rcept_bgn_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rcept_clse_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rgst_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ntce_instt_cd', sa.String(length=20), nullable=True),
    sa.Column('ntce_instt_nm', sa.String(length=200), nullable=True),
    sa.Column('dminstt_cd', sa.String(length=20), nullable=True),
    sa.Column('dminstt_nm', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('source_keyword', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_pre_specs_bf_spec_rgst_no'), 'bid_pre_specs', ['bf_spec_rgst_no'], unique=False)
    op.create_table('bid_pipeline_links',
    sa.Column('bid_type', sa.String(length=20), nullable=True),
    sa.Column('prcrmnt_req_no', sa.String(length=80), nullable=True),
    sa.Column('order_plan_unty_no', sa.String(length=80), nullable=True),
    sa.Column('bf_spec_rgst_no', sa.String(length=80), nullable=True),
    sa.Column('bid_ntce_no', sa.String(length=40), nullable=True),
    sa.Column('bid_ntce_ord', sa.String(length=10), nullable=True),
    sa.Column('cntrct_no', sa.String(length=80), nullable=True),
    sa.Column('notice_id', sa.String(), nullable=True),
    sa.Column('order_plan_id', sa.String(), nullable=True),
    sa.Column('pre_spec_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['bid_notices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_plan_id'], ['bid_order_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pre_spec_id'], ['bid_pre_specs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_pipeline_links_bf_spec_rgst_no'), 'bid_pipeline_links', ['bf_spec_rgst_no'], unique=False)
    op.create_index(op.f('ix_bid_pipeline_links_bid_ntce_no'), 'bid_pipeline_links', ['bid_ntce_no'], unique=False)
    op.create_index(op.f('ix_bid_pipeline_links_bid_type'), 'bid_pipeline_links', ['bid_type'], unique=False)
    op.create_index(op.f('ix_bid_pipeline_links_order_plan_unty_no'), 'bid_pipeline_links', ['order_plan_unty_no'], unique=False)
    op.create_index(op.f('ix_bid_pipeline_links_prcrmnt_req_no'), 'bid_pipeline_links', ['prcrmnt_req_no'], unique=False)
    # NOTE: n8n_executions 테이블은 코드상 모델이 제거됐지만 운영 데이터가 있을 수 있어 보존.
    # autogenerate가 drop 제안한 것을 의도적으로 제거.
    op.add_column(
        'bid_alerts',
        sa.Column('target_type', sa.String(length=20), nullable=False, server_default='notice'),
    )
    op.add_column('bid_alerts', sa.Column('order_plan_id', sa.String(), nullable=True))
    op.add_column('bid_alerts', sa.Column('pre_spec_id', sa.String(), nullable=True))
    op.alter_column('bid_alerts', 'notice_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_bid_alerts_notice_id'), 'bid_alerts', ['notice_id'], unique=False)
    op.create_index(op.f('ix_bid_alerts_order_plan_id'), 'bid_alerts', ['order_plan_id'], unique=False)
    op.create_index(op.f('ix_bid_alerts_pre_spec_id'), 'bid_alerts', ['pre_spec_id'], unique=False)
    op.create_index(op.f('ix_bid_alerts_target_type'), 'bid_alerts', ['target_type'], unique=False)
    op.create_foreign_key(None, 'bid_alerts', 'bid_pre_specs', ['pre_spec_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bid_alerts', 'bid_order_plans', ['order_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bid_alerts', type_='foreignkey')
    op.drop_constraint(None, 'bid_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_bid_alerts_target_type'), table_name='bid_alerts')
    op.drop_index(op.f('ix_bid_alerts_pre_spec_id'), table_name='bid_alerts')
    op.drop_index(op.f('ix_bid_alerts_order_plan_id'), table_name='bid_alerts')
    op.drop_index(op.f('ix_bid_alerts_notice_id'), table_name='bid_alerts')
    op.alter_column('bid_alerts', 'notice_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bid_alerts', 'pre_spec_id')
    op.drop_column('bid_alerts', 'order_plan_id')
    op.drop_column('bid_alerts', 'target_type')
    # n8n_executions 복원 단계는 upgrade에서 drop을 제거했으므로 함께 제거.
    op.drop_index(op.f('ix_bid_pipeline_links_prcrmnt_req_no'), table_name='bid_pipeline_links')
    op.drop_index(op.f('ix_bid_pipeline_links_order_plan_unty_no'), table_name='bid_pipeline_links')
    op.drop_index(op.f('ix_bid_pipeline_links_bid_type'), table_name='bid_pipeline_links')
    op.drop_index(op.f('ix_bid_pipeline_links_bid_ntce_no'), table_name='bid_pipeline_links')
    op.drop_index(op.f('ix_bid_pipeline_links_bf_spec_rgst_no'), table_name='bid_pipeline_links')
    op.drop_table('bid_pipeline_links')
    op.drop_index(op.f('ix_bid_pre_specs_bf_spec_rgst_no'), table_name='bid_pre_specs')
    op.drop_table('bid_pre_specs')
    op.drop_index(op.f('ix_bid_order_plans_order_plan_unty_no'), table_name='bid_order_plans')
    op.drop_table('bid_order_plans')
    # ### end Alembic commands ###
