"""add n8n_executions table

Revision ID: f997e804f4eb
Revises: 
Create Date: 2026-03-04 00:56:52.494999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f997e804f4eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('n8n_executions',
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('project_slug', sa.String(length=100), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('callback_received', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_executions_execution_id'), 'n8n_executions', ['execution_id'], unique=True)
    op.create_index('ix_n8n_executions_project_status', 'n8n_executions', ['project_slug', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_n8n_executions_project_status', table_name='n8n_executions')
    op.drop_index(op.f('ix_n8n_executions_execution_id'), table_name='n8n_executions')
    op.drop_table('n8n_executions')
    # ### end Alembic commands ###
